# Generated by Django 5.1.1 on 2024-09-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
