# Generated by Django 5.0.7 on 2024-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
