# Generated by Django 5.0.7 on 2024-09-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='profile_picture',
        ),
    ]
